
FROM node:22-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_INVENTARIO
ARG NEXT_PUBLIC_API_VENTAS
ARG NEXT_PUBLIC_API_FACTURACION
ARG NEXT_PUBLIC_FRONT_LOGIN
ARG NEXT_PUBLIC_FRONT_FACTURACION
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

COPY package*.json ./

RUN npm install

COPY . .

ENV NEXT_PUBLIC_API_INVENTARIO=$NEXT_PUBLIC_API_INVENTARIO
ENV NEXT_PUBLIC_API_VENTAS=$NEXT_PUBLIC_API_VENTAS
ENV NEXT_PUBLIC_API_FACTURACION=$NEXT_PUBLIC_API_FACTURACION
ENV NEXT_PUBLIC_FRONT_LOGIN=$NEXT_PUBLIC_FRONT_LOGIN
ENV NEXT_PUBLIC_FRONT_FACTURACION=$NEXT_PUBLIC_FRONT_FACTURACION
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]