version: '3.8'

services:
  app:
    # Instrucciones para construir la imagen Docker para este servicio.
    build:
      # El contexto de construcción es el directorio actual (donde se encuentra este docker-compose.yml y el Dockerfile).
      context: .
      dockerfile: Dockerfile 
      args:
        # Argumentos de construcción que se pasan al Dockerfile.
        NEXT_PUBLIC_API_INVENTARIO: ${NEXT_PUBLIC_API_INVENTARIO}
        NEXT_PUBLIC_API_VENTAS: ${NEXT_PUBLIC_API_VENTAS}
        NEXT_PUBLIC_API_FACTURACION: ${NEXT_PUBLIC_API_FACTURACION}
        NEXT_PUBLIC_FRONT_LOGIN: ${NEXT_PUBLIC_FRONT_LOGIN}
        NEXT_PUBLIC_FRONT_FACTURACION: ${NEXT_PUBLIC_FRONT_FACTURACION}
    # El puerto 3000 del host se mapea al puerto 3000 del contenedor,
    # permitiendo acceder a tu aplicación desde tu máquina local (ej. http://localhost:3000).
    ports:
      - "3000:3000"
    
    # Asigna un nombre específico al contenedor para una fácil identificación.
    container_name: front-ventas-local-mirror
    
    # Política de reinicio: el contenedor se reiniciará automáticamente a menos que sea detenido explícitamente.
    # Útil para desarrollo si el contenedor falla, pero puedes ajustarlo según tu preferencia.
    restart: unless-stopped
    
    # Opcional: Define variables de entorno específicas para el contenedor en desarrollo.
    # Por ejemplo, para configurar el entorno de Node.js.
    #env_file:
    # - .env.local # Carga las variables de entorno desde un archivo .env en el directorio actual
