apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ventas
  labels:
    app: frontend-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ventas
  template:
    metadata:
      labels:
        app: frontend-ventas
    spec:
      containers:
        - name: frontend-ventas
          image: southamerica-east1-docker.pkg.dev/construtem/microservicios-construtem/frontend-ventas:latest
          ports:
          ports:
            - containerPort: 3000
