apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ventas-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ventas.tssw.cl
      secretName: front-ventas-tls
  rules:
    - host: ventas.tssw.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-ventas-service
                port:
                  number: 80
