apiVersion: v1
kind: Service
metadata:
  name: frontend-ventas-service
spec:
  selector:
    app: frontend-ventas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
