name: Frontend CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar build
      run: npm run build

    - name: Ejecutar linter
      run: npm run lint
